"""del arch

Revision ID: 186ad1e21221
Revises: bbb3c78d32e4
Create Date: 2022-09-16 14:19:04.734036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '186ad1e21221'
down_revision = 'bbb3c78d32e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('archives')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('archives',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('description', sa.VARCHAR(length=200), nullable=False),
    sa.Column('transferred', sa.DATETIME(), nullable=True),
    sa.Column('tag', sa.VARCHAR(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
